### PR TITLE
606 show timeframe

### LINKED ISSUE #606: Show timeframe in tc overview
As an editor
i want to see the timeframe in tc overview-list (as a symbol?)
in order to faster get an overview.

### PR DESCRIPTION
**Pull request by tillprochaska**
The timeframe will now be displayed in the text components listing as well.

@matthib: I know this [regex replacement](https://github.com/roschaefer/story.board/blob/606_show_timeframe/app/views/text_components/_table_row.html.haml#L14) is quite dirty, I didn’t want to refactor the[ part of the model](https://github.com/roschaefer/story.board/blob/606_show_timeframe/app/models/text_component.rb#L2-L9) where those labels are generated…

@drjakob: Unfortunately I didn’t find a good way to indicate the timeframe using icons or anything else, but I think simple text is actually a good and unambigous solution in this case.

bildschirmfoto 2017-09-02 um 17 05 54

close #606

### CODE REVIEW

**Comment by drjakob** [comment]
Ok, danke

**Comment by tillprochaska** [comment]
@matthib: Thanks for the review!

Adding a helper method to a decorator or to the model directly that returns either a short or a detailed label for the timeframe would probably clean up things a bit. But I’ll leave it as is for now.

For the second part: Yep, and I think there already is an issue which is pretty similar to your idea: #374. We’ve talked about this in our last phone conference and there where worries that checking the current status for every text component might cause performance issues. Highlighting text components based only on the current time and day should required less database queries etc., but might also be confusing. @drjakob, any thoughts on this? But this is probably  a separate user story anyways.

**Comment by matthib** [comment]
@tillprochaska Yes you are right, I remember talking about that the check for "green light" for every text component would cause a big performance impact. But maybe displaying the current timeframe and day would help as an orientation which text component is active at which point in time. Otherwise you always have to look up what the exact duration of the timeframes is and also know which day the project is currently on. I don't know if I'm the only one getting confused by this, but I guess I would have to double check all the time, to make sure I've set the day and the timeframe correctly.

**Comment by tillprochaska** [comment]
I’m totally with you. My preferred solution would still be the active flash light (which is actually very easy to implement, so we could just try this and see if it actually has a relevant impact on the performance). Displaying the current day since the start date of the project as well as the current time frame seems to be a good alternative to me.

Let’s hear what Jakob or the editors think about this. I think this isn’t crucial for the project start so we could implement this later… ;)

**Pull request merged**
