### PR TITLE
348 active report

### LINKED ISSUE #348: TextComponents: Default filter by active report
As a reporter
I want to see ONLY the text.components, triggers and sensors for the selected report
in order to avoid confusion

### PR DESCRIPTION
**Pull request by roschaefer**
close #348

What is **NOT** included: 
1. `/report/present/:id` is really creating a individual report
2. Chatfuel API is taking `report_id` into account

Also I don't like the appearance of the big box on the right

Another thing which might feel strange: If the user visits a page that is not under `/reports/:id` the active report will be reset to the default report

### CODE REVIEW

**Comment by roschaefer** [comment]
@tillprochaska @matthib I know this is quite a massive PR, maybe one of you could give me a review nevertheless

**Comment by roschaefer** [comment]
@matthib you're totally right - I just forgot

**Comment by roschaefer** [comment]
@matthib can you give me another review maybe?

**Comment by tillprochaska** [comment]
@roschaefer: I’m currently on vacation and will be back tomorrow. There are a lot of things on my to do list, but I’ll try to send you my review as soon as possible!

**Comment by matthib** [comment]
After the lasts commits only sensors and reports for the active report are shown, as requested in the original issue  #348. I don't have any other complaints, I think this PR can be merged.

**Comment by roschaefer** [comment]
@matthib can you approve this PR then? :smile: there is a button on Github

**Comment by tillprochaska** [comment]
Okay, it seems I’m a little late to the party again. But as @matthib has approved and you merged the PR it’s not necessary anymore that I’m explicitly approving the changes. However, I had a look at the changes for learning purposes… ;)

**Pull request merged**
