### PR TITLE
[WIP] 336 text component modal

### LINKED ISSUE #330: tc Channel select: Sensorstory as a default
As a reporter
I want sensorstory as the default channel
in order to save one click.

### LINKED ISSUE #336: Structure of create text.component modal
As a reporter
I want the create text.component better structured
in order to better distinguish the different parts.
(And think about the field in #316)
## FILE
Report
Assignee
Status

## TRIGGER
Define a new Trigger first.
Name

### Topic
...choose a topic 

~~Trigger group Not implemented~~
Color
### Sensor conditions
Add sensor
Additional conditions
Timeliness constraint
Text component will be triggered for sensor readings within the last X hours

### Priority

From hour

To hour

### Time Span
From day To day
### ARTICLE
Please write the text here. To add dynamic fields, like temperature values via toolbar.
 Ingredients 

Title

Introduction

Main part

~~Closing~~

### QUESTIONS/ANSWERS ~~for Chatfuel~~
Add a question and an answer for Chatfuel and/or Nerdbutton.
## OUTPUT
* Channels
chatbot
sensorstory(DEFAULT)

### COMMUNICATION
communication field

** [BUTTON] Create Text component **

### PR DESCRIPTION
**Pull request by tillprochaska**
Please DO NOT merge yet. Current progress:

I’ve tried several options and I actually like this one. I split the form into four steps/pages. For me, this makes the form way easier to skim. However, I’m not sure if this is of any actual use for power users, that add/edit many text components at once.

bildschirmfoto 2017-06-19 um 20 46 34

As an possible alternative I’ve also played with an accordion-like solution, where only one form section at a time is expanded.

bildschirmfoto 2017-06-19 um 21 01 38

Would really like to hear your opinions on this, @drjakob & @CowboyBjoern.

close #336 
close #330

### CODE REVIEW

**Comment by drjakob** [comment]
3 of 3 votes for the accordion-like solution

**Comment by drjakob** [comment]
Default should be "use existing trigger"

**Comment by tillprochaska** [comment]
Hey @roschaefer! I changed quite some markup in this PR which is why some test are/were failing. I tried to fix the remaining test, however I’m stuck at this point. Most tests are failing because the relevant dom node can’t be found. However, if I inspect the html screenshot capybara creates, I can find those dom elements using `document.querySelector('selector')` in my browser. Could you have a look at this?

**Comment by drjakob** [comment]
Please solve this, this is important for production.

**Comment by drjakob** [comment]
Can we finally merge this great improvement?

**Comment by drjakob** [comment]
(Und was ist mit dem Wasserschwein passiert?

**Pull request merged**
