### PR TITLE
157 end date of report

### LINKED ISSUE #157: Report: End date of report
As a reporter
I want to set an end date of my report
So text components can be aligned along a linear schedule

For convenience, the end date could also be entered in days
related: #156

### PR DESCRIPTION
**Pull request by roschaefer**
close #157

### CODE REVIEW

**Comment by roschaefer** [comment]
@drjakob it is actually difficult to implement the change of end date via a duration (javascript, two way data binding). Just editing the end date and see the duration afterwards will do it also, I guess

**Comment by drjakob** [comment]
Not sure about this one. Is this just about input?
Otherwise: The reports property "duration" is totally independent from concrete dates.

**Comment by roschaefer** [comment]
The duration of an experiment is `end_date - start_date`. No?

Have a look into the cucumber feature.

**Comment by drjakob** [comment]
No. First step: Define duration. (Compose & write everything). Second step: define a start_date.

**Comment by roschaefer** [comment]
Ok. So `duration` is always an integer (in days)?

**Comment by drjakob** [comment]
Yes. That simple.

**Pull request merged**
