### PR TITLE
Change evening timeframe from 18-0h, change nights timeframe to 0-6h

### LINKED ISSUE #677: CONFLICT: night timeframe conflicting in planing with days
There is a conflict with timeframe night (23-6 o'clock) and days.

As an editor 
planing to publish a tc in the night of day 3 to 4 I choose timeframe night (23-6) and day 3 to four.
BUT then tc will also be active from 23-23:59) on day 4.
Possible Solution: changeing night-timeframe to 0-6 
 
What do you think?

### PR DESCRIPTION
**Pull request by matthib**
Change evening timeframe from 18-0h, change nights timeframe to 0-6h as proposed by @drjakob in #677 

@tillprochaska Do you know if changing the timeframes in the text_component model is sufficient, or do I need to make more changes for the new timeframes to get triggered properly?

--- 

Close #677

### CODE REVIEW

**Comment by tillprochaska** [comment]
Hey @matthib: I haven’t had a closer look at this, but I think we need a rake task to update existing text components. (It’s not the timeframe that’s saved to the db but the actual from and to hours the timeframe is mapping to.)

**Comment by drjakob** [comment]
Rake task sound plausible to me.

**Comment by tillprochaska** [comment]
Yep, that's probably the best way!

**Comment by matthib** [comment]
@tillprochaska Yep, you're right, the text_components from_hour and to_hour needs to be changed for the concerning text_components. 
With the last commit I add a rake task to do exactly that.

**Comment by roschaefer** [comment]
A `migration` would have been the better choice here. Why? We need to change all the data, no matter if `development`, `test` (hopefully empty, anyways) or `production`.

**Pull request merged**
